#!/bin/bash

bare_vers=$(echo $1 | sed -e 's/slurm-//g')
major=$(echo $1 | awk -F '-' '{print $2}')
feature=$(echo $1 | awk -F '-' '{print $3}')
minor=$(echo $1 | awk -F '-' '{print $4}')
bugfix=$(echo $1 | awk -F '-' '{print $5}')

if [ $bugfix -gt 1 ]; then
  echo "${major}.${feature}.${minor}.${bugfix}"
else
  echo "${major}.${feature}.${minor}"
fi
